import type { NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
	return (
		<div className="flex flex-col items-center justify-center">
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<div className="flex flex-1 flex-col justify-center items-center"></div>

			<footer className="flex flex-1 py-4 justify-center">
				<small>&copy; {`${new Date().getFullYear()} foobar.`}</small>
			</footer>
		</div>
	);
};

export default Home;
